# litellm settings
# https://docs.litellm.ai/docs/simple_proxy#litellm-settings-config-file

# litellm-settings.yaml
litellm_settings:
  set_verbose: True
  cache: False
  drop_params: True
  num_retries: 2
model_list:
  - model_name: gpt-oss-20b
    litellm_params: 
      model: openai/gpt-oss-20b
      api_base: https://qllm.iselab.info/v1
      api_key: none # does os.getenv("AZURE_API_KEY_EU")